### ISSUE TITLE
Crash on creating new character

### ISSUE THREAD

**Issue by rikardg** [gregersn/whathappened#727]
Tested on current `master`, f1cbf458303ddcb7673ab43bb0cbec8bf5e2b1da . Not technically a clean checkout, but I did `git clean -xdf`.

Steps:
- `make dev_server`
- Go to localhost:5000
- Create account
- Create (character) -> Drakar och Demoner, e.g. with title "foo"

Application crashes with `jinja2.exceptions.UndefinedError: 'field' is undefined`.

From a quick commenting-out-some-code, it looks like it's related to the rendering of Viljepoäng, Kroppspoäng, Rustning or Hjälm in `src/whathappened/templates/character/general_character.html.jinja:102`; commenting out the `render_item` in the `render_section_2` macro keeps it from crashing.

**Comment by gregersn** [comment]
Wrong parameter was used when calling macro to render progress-checkpoint-widget.

Fixed in e772d4c7e4f4d3af71891b63633d11c24e172fbb
